Importando a biblioteca e lendo o arquivo csv

In [9]:
pip install pandas

Requirement already satisfied: pandas in c:\users\casa\appdata\local\programs\python\python314\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\casa\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\casa\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\casa\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\casa\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("train.csv")

Observando o dataframe correspondente da base de dados do Walmart

In [12]:
df.head(100)

    Store  Dept        Date  Weekly_Sales  IsHoliday
0       1     1  2010-02-05      24924.50      False
1       1     1  2010-02-12      46039.49       True
2       1     1  2010-02-19      41595.55      False
3       1     1  2010-02-26      19403.54      False
4       1     1  2010-03-05      21827.90      False
..    ...   ...         ...           ...        ...
95      1     1  2011-12-02      25293.49      False
96      1     1  2011-12-09      33305.92      False
97      1     1  2011-12-16      45773.03      False
98      1     1  2011-12-23      46788.75      False
99      1     1  2011-12-30      23350.88       True

[100 rows x 5 columns]

Selecionando apenas a loja 3 para fazermos as análises

In [13]:
df_loja_3 = df[df['Store'] == 3]

In [14]:
df_loja_3

       Store  Dept        Date  Weekly_Sales  IsHoliday
20482      3     1  2010-02-05       6453.58      False
20483      3     1  2010-02-12      12748.72       True
20484      3     1  2010-02-19       8918.31      False
20485      3     1  2010-02-26       4992.00      False
20486      3     1  2010-03-05       5172.73      False
...      ...   ...         ...           ...        ...
29513      3    98  2012-06-01         49.50      False
29514      3    98  2012-06-29         94.50      False
29515      3    98  2012-07-06         40.50      False
29516      3    98  2012-07-13          9.00      False
29517      3    98  2012-08-03         21.50      False

[9036 rows x 5 columns]

In [15]:
df_loja_3['Dept'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 38, 40, 41, 42, 44, 45, 46, 47, 49, 51, 52, 54, 55, 56, 59, 60,
       67, 71, 72, 74, 77, 78, 79, 80, 81, 82, 83, 85, 87, 90, 91, 92, 94,
       95, 96, 97, 98])

In [16]:
dept_sales = df_loja_3.groupby("Dept")['Weekly_Sales'].sum().sort_values(ascending = False)

Selecionando as 10 categorias que mais vendem

In [17]:
dept_sales.head(10) #observando quais são os 10 departamentos que mais vendem da loja 3

Dept
38    15529566.07
72     3259950.49
40     2603044.48
2      2408373.92
95     2251610.54
5      1672437.42
13     1624917.82
23     1560606.20
10     1554688.01
7      1436340.85
Name: Weekly_Sales, dtype: float64

In [18]:
#colocando nome em cada categoria de acordo com a empresa
map_dept = {
    38: 'Mercearia Seca',
    72: 'Higiene Pessoal',
    40: 'Eletronicos',
    2: 'Produtos de Limpeza',
    95: 'Padaria e Confeitaria',
    5: 'Carnes e Congelados',
    13: 'Laticinios',
    23: 'Hortifruti',
    10: 'Pet Shop',
    7: 'Utilidades Domésticas'
}

df_loja_3['Category'] = df_loja_3['Dept'].map(map_dept)

In [19]:
df_loja_3_dept = df_loja_3[df_loja_3['Dept'].isin([38, 72, 40, 2, 95, 5, 13, 23, 10, 7])] #selecionando apenas as categorias que são as mais vendidas

In [20]:
df_loja_3_dept

       Store  Dept        Date  Weekly_Sales  IsHoliday               Category
20625      3     2  2010-02-05      17566.72      False    Produtos de Limpeza
20626      3     2  2010-02-12      15177.30       True    Produtos de Limpeza
20627      3     2  2010-02-19      15676.11      False    Produtos de Limpeza
20628      3     2  2010-02-26      15112.23      False    Produtos de Limpeza
20629      3     2  2010-03-05      16477.28      False    Produtos de Limpeza
...      ...   ...         ...           ...        ...                    ...
29194      3    95  2012-09-28      17969.39      False  Padaria e Confeitaria
29195      3    95  2012-10-05      18115.89      False  Padaria e Confeitaria
29196      3    95  2012-10-12      16847.92      False  Padaria e Confeitaria
29197      3    95  2012-10-19      16784.09      False  Padaria e Confeitaria
29198      3    95  2012-10-26      17210.73      False  Padaria e Confeitaria

[1430 rows x 6 columns]

In [21]:
df_loja_3_dept['IsHoliday'].value_counts() #percebo que apenas 100 semanas das 1430 tem feriado

IsHoliday
False    1330
True      100
Name: count, dtype: int64

In [22]:
df_loja_3_dept.groupby('IsHoliday')['Weekly_Sales'].mean()

#Ao analisar as vendas em semanas com feriados, é notavel que semanas que contém feriados tem resultados superiores as que não tem

IsHoliday
False    23547.686406
True     25831.128800
Name: Weekly_Sales, dtype: float64

In [23]:
df_loja_3_dept.groupby('IsHoliday')['Weekly_Sales'].median() #verificando possiveis outliers, percebe-se que não influenciaram na Análise

IsHoliday
False    13953.625
True     14129.375
Name: Weekly_Sales, dtype: float64

In [24]:
df_loja_3_dept.groupby('Date')['Weekly_Sales'].sum()

Date
2010-02-05    297653.68
2010-02-12    246688.85
2010-02-19    248590.52
2010-02-26    260662.77
2010-03-05    263398.21
                ...
2012-09-28    222442.20
2012-10-05    263369.74
2012-10-12    235586.67
2012-10-19    243740.66
2012-10-26    230075.51
Name: Weekly_Sales, Length: 143, dtype: float64

In [25]:
df_loja_3.info() #vendo que a coluna data está em string

<class 'pandas.DataFrame'>
RangeIndex: 9036 entries, 20482 to 29517
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         9036 non-null   int64
 1   Dept          9036 non-null   int64
 2   Date          9036 non-null   str
 3   Weekly_Sales  9036 non-null   float64
 4   IsHoliday     9036 non-null   bool
 5   Category      1430 non-null   str
dtypes: bool(1), float64(1), int64(2), str(2)
memory usage: 361.9 KB

In [26]:
df_loja_3_dept['Date'] = pd.to_datetime(df_loja_3_dept['Date']) #convertendo para datatime
df_loja_3_dept.info()

<class 'pandas.DataFrame'>
Index: 1430 entries, 20625 to 29198
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         1430 non-null   int64
 1   Dept          1430 non-null   int64
 2   Date          1430 non-null   datetime64[us]
 3   Weekly_Sales  1430 non-null   float64
 4   IsHoliday     1430 non-null   bool
 5   Category      1430 non-null   str
dtypes: bool(1), datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 68.4 KB

In [27]:
df_loja_3_dept['Year'] = df_loja_3_dept['Date'].dt.year #criando a coluna Year, para analisar por ano
df_loja_3_dept['Month'] = df_loja_3_dept['Date'].dt.month_name()
df_loja_3_dept

,Store,Dept,Date,Weekly_Sales,IsHoliday,Category,Year,Month
20625,3,2,2010-02-05,17566.72,False,Produtos de Limpeza,2010,February
20626,3,2,2010-02-12,15177.30,True,Produtos de Limpeza,2010,February
20627,3,2,2010-02-19,15676.11,False,Produtos de Limpeza,2010,February
20628,3,2,2010-02-26,15112.23,False,Produtos de Limpeza,2010,February
20629,3,2,2010-03-05,16477.28,False,Produtos de Limpeza,2010,March
...,...,...,...,...,...,...,...,...
29194,3,95,2012-09-28,17969.39,False,Padaria e Confeitaria,2012,September
29195,3,95,2012-10-05,18115.89,False,Padaria e Confeitaria,2012,October
29196,3,95,2012-10-12,16847.92,False,Padaria e Confeitaria,2012,October
29197,3,95,2012-10-19,16784.09,False,Padaria e Confeitaria,2012,October
29198,3,95,2012-10-26,17210.73,False,Padaria e Confeitaria,2012,October

Ao analisar o ano de 2012, observa-se que esse período apresentou menor
variabilidade das vendas semanais quando comparado a 2010 e 2011, indicando
um comportamento mais estável ao longo do ano. Além disso, 2012 registrou
a maior média e a maior mediana de vendas semanais para a loja 3, o que
sugere um desempenho médio superior, com menor influência de eventos
externos extremos.

Entretanto, apesar desse desempenho médio mais elevado, o volume total de
vendas em 2012 foi inferior aos anos anteriores, o que se explica pelo
menor número de semanas contabilizadas no dataset. Dessa forma, a análise
reforça a importância de considerar simultaneamente métricas de tendência
central, dispersão e volume ao interpretar os resultados.

In [28]:
df_loja_3_dept.groupby('Year')['Weekly_Sales'].sum().sort_values(ascending=False)

Year
2011    12302595.38
2010    11380543.23
2012    10218397.19
Name: Weekly_Sales, dtype: float64

In [29]:
df_loja_3_dept['Year'].value_counts()

Year
2011    520
2010    480
2012    430
Name: count, dtype: int64

In [30]:
df_loja_3_dept.groupby('Year')['Weekly_Sales'].mean().sort_values(ascending= False)

Year
2012    23763.714395
2010    23709.465062
2011    23658.837269
Name: Weekly_Sales, dtype: float64

In [31]:
df_loja_3_dept.groupby('Year')['Weekly_Sales'].median().sort_values(ascending= False)

Year
2012    16044.840
2011    14076.790
2010    12457.925
Name: Weekly_Sales, dtype: float64

In [32]:
df_loja_3_dept.groupby('Year')['Weekly_Sales'].std()

Year
2010    34343.133309
2011    29428.711602
2012    23401.774724
Name: Weekly_Sales, dtype: float64

Apesar de julho ser um dos meses com maior número de registros no sistema,
seu desempenho é inferior aos demais, pois as vendas concentram-se em
categorias de baixo valor agregado, como mercearia seca e produtos de consumo
recorrente.

Em contrapartida, dezembro apresenta alto desempenho, impulsionado por
categorias de maior valor agregado, comportamento fortemente associado a
datas comemorativas e compras sazonais.

Observa-se também que novembro apresenta elevado desvio padrão, indicando
alta variabilidade nas vendas semanais. Esse comportamento pode ser explicado
pela Black Friday, que ocorre na última sexta-feira do mês, gerando picos de
vendas pontuais.

Esses resultados sugerem que o comportamento do consumidor é fortemente
influenciado por preço e eventos promocionais. Estratégias como a criação de
kits, ações promocionais e o estímulo ao cross-sell podem contribuir para o
aumento do ticket médio e melhorar o desempenho dos meses mais fracos.

In [ ]:
#Contabilizando a quantidade de registros de cada mês

df_loja_3_dept['Month'].value_counts()

Month
April        140
July         140
March        130
June         130
August       130
September    130
October      130
February     120
May          120
December     100
November      80
January       80
Name: count, dtype: int64

In [47]:
# Calcula métricas mensais para comparar volume e desempenho médio

df_loja_3_dept.groupby('Month')['Weekly_Sales'].sum().sort_values(ascending=False)

Month
April        3212905.21
July         3140141.17
February     3124557.82
March        3083916.35
June         3043935.27
October      2993662.92
September    2982166.60
August       2946162.90
May          2743430.64
December     2701962.45
November     2104216.04
January      1824478.43
Name: Weekly_Sales, dtype: float64

In [ ]:
#Calculando a média de cada mês, levando em consideração que a média pode ser influenciada por outliers

df_loja_3_dept.groupby('Month')['Weekly_Sales'].mean().sort_values(ascending= False)

Month
December     27019.624500
November     26302.700500
February     26037.981833
March        23722.433462
June         23414.886692
October      23028.176308
April        22949.322929
September    22939.743077
May          22861.922000
January      22805.980375
August       22662.791538
July         22429.579786
Name: Weekly_Sales, dtype: float64

In [ ]:
#Calculando a mediana de cada mês

df_loja_3_dept.groupby('Month')['Weekly_Sales'].median().sort_values(ascending= False)

Month
December     17078.865
June         15300.330
March        14252.685
February     14229.675
October      13918.310
August       13894.690
July         13875.075
May          13789.300
November     13769.110
September    13662.530
April        12846.210
January      11747.635
Name: Weekly_Sales, dtype: float64

In [ ]:
#Observando o desvio padrão referente aos meses registrados

df_loja_3_dept.groupby('Month')['Weekly_Sales'].std().sort_values(ascending= False)

Month
February     32367.647961
January      31604.513805
April        31413.374587
November     31219.222832
March        30354.197892
December     29988.984372
May          29281.904769
September    29081.071023
October      28719.767383
July         28402.869972
August       27950.735180
June         26451.342898
Name: Weekly_Sales, dtype: float64

In [ ]:
#Observando quantos feriados teve em cada mês e se os dados estão sendo influenciados por isso

df_loja_3_dept.groupby('Month')['IsHoliday'].sum()

Month
April         0
August        0
December     20
February     30
January       0
July          0
June          0
March         0
May           0
November     20
October       0
September    30
Name: IsHoliday, dtype: int64

In [77]:
df_loja_3_filtrado = df_loja_3_dept[df_loja_3_dept['Month'].isin(['November'])]

df_loja_3_filtrado.groupby(['Month', 'Category'])['Weekly_Sales'].sum().sort_values(ascending=False)

Month     Category
November  Mercearia Seca           851432.28
          Higiene Pessoal          328138.30
          Carnes e Congelados      156789.29
          Eletronicos              144689.65
          Produtos de Limpeza      126424.53
          Utilidades Domésticas    120994.94
          Padaria e Confeitaria    102666.01
          Hortifruti               100548.84
          Laticinios                87792.87
          Pet Shop                  84739.33
Name: Weekly_Sales, dtype: float64